const MainActionTypes = {
    TOGGLE_SHOWN_STORIES: 'TOGGLE_SHOWN_STORIES',
    SET_PRODUCTS_LIST: 'SET_PRODUCTS_LIST',
    CHANGE_CHOOSEN_EGG : 'CHANGE_CHOOSEN_EGG'
};

export default MainActionTypes;
